#!/usr/bin/env bash 

# Disable ipV6
# Change TTL

sudo -v
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -w net.ipv6.conf.lo.disable_ipv6=1
iptables -t mangle -A POSTROUTING -j TTL --ttl-set 65
sudo -k
