#!/bin/env bash

echo -e "-----\t-------"
echo -e "Usage\tFile(s)"
echo -e "-----\t-------"
mapfile -t du_output < <(du -sh -c "$@" 2>/dev/null | sort -hr)
echo -e "${du_output[0]}"
echo -e "-----\t-------"

for entry in "${du_output[@]:1}"; do
  printf "${entry}"
  printf "\n"
done
